### ISSUE TITLE
Problems in connecting to Beckhoff PLC CX9020

### ISSUE THREAD

**Issue by stefanocovino** [chwiede/pyads#1]
Dear friends,

I have download and installed the pyads library on a linux PC running Fedora. No problem from this side.

However, when I try to connect to a Beckhoff PLC using one of the examples provided in the zip file (deviceinfo.py) on the local network I simply get this message:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 530, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 483, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyads/adsclient.py", line 80, in _AsyncRead
    if (newPacket.InvokeID == self._CurrentInvokeID):
AttributeError: 'NoneType' object has no attribute 'InvokeID'

Traceback (most recent call last):
  File "deviceinfo.py", line 5, in <module>
    info = device.ReadDeviceInfo()
  File "/usr/local/lib/python2.7/site-packages/pyads/adsclient.py", line 182, in ReadDeviceInfo
    return DeviceInfoCommand().Execute(self)
  File "/usr/local/lib/python2.7/site-packages/pyads/commands/adscommand.py", line 36, in Execute
    responsePacket = adsClient.SendAndRecv(packet)
  File "/usr/local/lib/python2.7/site-packages/pyads/adsclient.py", line 134, in SendAndRecv
    return self.AwaitCommandInvoke()
  File "/usr/local/lib/python2.7/site-packages/pyads/adsclient.py", line 170, in AwaitCommandInvoke
    raise Exception("Timout: could not receive ADS Answer!")
Exception: Timout: could not receive ADS Answer!

Can you help me to understand where the problem is?

Best regards,
    Stefano

**Comment by PyRule** [comment]
Hello chwiede,

I have an option to buy a C6330 IPC complete with twincat license.  Will pyads work with it?

Best regards,

Roel

**Comment by chwiede** [comment]
Hello Roel,

i can't guarantee for this. If you can communicate with your IPC via ADS, pyads may communicate with your IPC. Running pyads *on* your IPC doesn't make sense for me, because you have to run it on Windows with TwinCat PLC anyway.

I'd developed this library for a simple buscoupler (without os), and i can't test every device.

Best of luck,

Christoph

**Comment by PyRule** [comment]
Hi Chistoph,

Thanks, I don't need it to run on the IPC itself so that's fine.  I want
the unit becuase it has ethercat.
So can I connect remotely to the IPC and use pyads, or do I really need a
buscoupler unit for example an ethercat buscoupler?

Best reagrds,

Roel

2015-02-01 10:32 GMT+01:00 Christoph Wiedemann <notifications@github.com>:

**Comment by chwiede** [comment]
Hi,

if your IPC as a running PLC or "runtime system", you might be able to communicate (read variables, write variables) with it over pyads. Communication with a soft-sps also works.

*But i cannot garantuee for anything, because i'm not affiliated with Beckhoff in any way.*

The buscouple BC9100 is not needed - but it's the only device which i can test.
