### ISSUE TITLE
Unable to Connect Beckhoff CX9020 PLC

### ISSUE THREAD

**Issue by sameer546** [chwiede/pyads#19]
I'm using the deviceinfo.py code for reading the device info of the plc..I'm using CX9020 plc
IP Address of PLC: 192.168.0.60
amsnetid : 5.35.137.56.1.1
port: 801

from pyads import *  
with AdsDevice(amsTarget="5.35.137.56.1.1:801") as device:
    info = device.ReadDeviceInfo()
    print(info)

Error: 
Traceback (most recent call last):
 File "first_contact.py", line 4, in <module>
   info = device.ReadDeviceInfo()
 File "build/bdist.linux-armv7l/egg/pyads/adsclient.py", line 201, in ReadDeviceInfo
 File "build/bdist.linux-armv7l/egg/pyads/commands/adscommand.py", line 36, in Execute
 File "build/bdist.linux-armv7l/egg/pyads/adsclient.py", line 131, in SendAndRecv
 File "build/bdist.linux-armv7l/egg/pyads/adsclient.py", line 69, in Connect
pyads.adsexception.AdsException: 'A socket operation was attempted to an unreachable host'

Can anyone help me out in resolving this error??

**Comment by ccatterina** [comment]
Hello, 
If the PLC IP address is different from the first four octects of the AmsNetID, you must specify the ```targetIP``` argument:

```python
from pyads import *
with AdsDevice(amsTarget="5.35.137.56.1.1:801", targetIP="192.168.0.60") as device:
info = device.ReadDeviceInfo()
print(info)
```

**Comment by sameer546** [comment]
@ccatterina 1. I'm running the above code in a linux based system, Will it work?
2. Can you help me in understanding this : ""Remember: You have to insert your client AMS-ID into the ams table of your target device!""

**Comment by ccatterina** [comment]
>  I'm running the above code in a linux based system, Will it work?

Yes, I use this package with a raspberry pi.

> Can you help me in understanding this : ""Remember: You have to insert your client AMS-ID into the ams table of your target device!"

Ok, it means that you must insert the AMS Net ID of your system (the machine where pyads is installed) in the routes table on the CX9020.

In the Twincat System Manager, select the target, in the left menu, under System Configuration, you should find Route Settings.

Select static routes and then add a new route with the AMS Net ID and IP Address of your client system.

**Comment by sameer546** [comment]
![issue2](https://user-images.githubusercontent.com/18327543/36947286-b3f2a4ac-1fef-11e8-99cf-05b3d42165e0.JPG)
Thanks a lot @ccatterina that makes sense..

Could u please help me out in the add route settings, I have attached a snapshot..based on the numbers just guide me what should I fill in those areas...
After Doing this Do I need to install anymore library files or pyads is enough??

**Comment by ccatterina** [comment]
1. A name of your choice.
2. The Ams Net ID of your client system (```0.0.0.0.0.0``` if you don't specify the ```amsSource``` in the code example, otherwise the AmsNetID of the ```amsSource``` specified)
3. TCP/IP.
4. The IP address of yout client system.
5. Static.
6. None.
7. Leave it.

> After Doing this Do I need to install anymore library files or pyads is enough??

pyads is enough.

**Comment by sameer546** [comment]
@ccatterina : Thanks a lot..We routed using plc directly.
One more query: Did you captured the CX9020 time and date, if Yes what are the variable names which we can query? Please let me know about it..

**Comment by ccatterina** [comment]
Sorry for the late reply, i was a bit busy last week.

Btw I never tried to get time and date from the CX9020.
If there was a way to set a variable with the datetime in the CX9020, you can get that variable value using pyads.

Tomorrow i'll make a test.

**Comment by ccatterina** [comment]
[Here]( https://infosys.beckhoff.com/english.php?content=../content/1033/tcplclibutilities/html/TcPlcLibUtilities_SYSTEMTIME_TO_STRING.htm&id=) you can find a function block that retrieves system time as a string.
 
If you assign the result of this FB to a global variable called, for example, ```sysdt```, you can get it using ```pyads``` in this way:

```python
device.ReadByName('.sysdt', AdsDatatype.String)
```
